### ISSUE TITLE
PyRing : Invalid Input

### ISSUE THREAD

**Issue by Doudy** [JaniniRami07/PyRing#1]
Hello,
When i select 1, 2 or 3
`Select: 1--> Camera Check  2--> For Motion Footage 3--> To Get Motion Alerts: 1
`
I have following message !
`Invaild Input!!
`

**Comment by JaniniRami07** [comment]
Make sure to just enter the number by its self without spaces!

**Comment by Doudy** [comment]
I do 
`Select: 1--> Camera Check  2--> For Motion Footage 3--> To Get Motion Alerts:1
`
without spaces
I have `Invaild Input!!
`
I put the script in
`~/domoticz/scripts/python/python-ring-doorbell-master/scripts $`
I run the script with 
` sudo python PyRing.py`

**Comment by JaniniRami07** [comment]
Im not sure what is your problem because I have tried it on both kali linux and windows machines and they both worked, are you using python3?

**Comment by Doudy** [comment]
I am working with Raspberry
My Python version :
`$ python --version
Python 2.7.3
`
`$ python3 --version
Python 3.5.3`

When i start with 
`~/domoticz/scripts/python/python-ring-doorbell-master/scripts $ sudo python3 PyRing.py
`
i have following message:
 `Traceback (most recent call last):
  File "PyRing.py", line 2, in <module>
    from ring_doorbell import Ring
ImportError: No module named 'ring_doorbell'
`
??

**Comment by JaniniRami07** [comment]
First type: pip3 install ring_doorbell 
then python3 PyRing.py

**Comment by Doudy** [comment]
I have following your instructions 
`~/domoticz/scripts/python/python-ring-doorbell-master/scripts $ python3 PyRing.py

          ___       ___  _
          / _ \__ __/ _ \(_)__  ___ _
        / ___/ // / , _/ / _ \/ _ `/
        /_/   \_, /_/|_/_/_//_/\_, /
            /___/            /___/
                Authur:Rami Janini
                         v.1.0

Select: 1--> Camera Check  2--> For Motion Footage 3--> To Get Motion Alerts:1
============
~/domoticz/scripts/python/python-ring-doorbell-master/scripts $ python3 PyRing.py

          ___       ___  _
          / _ \__ __/ _ \(_)__  ___ _
        / ___/ // / , _/ / _ \/ _ `/
        /_/   \_, /_/|_/_/_//_/\_, /
            /___/            /___/
                Authur:Rami Janini
                         v.1.0

Select: 1--> Camera Check  2--> For Motion Footage 3--> To Get Motion Alerts:2

Traceback (most recent call last):
  File "PyRing.py", line 77, in <module>
    startProgram()
  File "PyRing.py", line 69, in startProgram
    GetVideo()
  File "PyRing.py", line 26, in GetVideo
    stickupCamera = myring.stickup_cams[0]
IndexError: list index out of range
=================
~/domoticz/scripts/python/python-ring-doorbell-master/scripts $ python3 PyRing.py

          ___       ___  _
          / _ \__ __/ _ \(_)__  ___ _
        / ___/ // / , _/ / _ \/ _ `/
        /_/   \_, /_/|_/_/_//_/\_, /
            /___/            /___/
                Authur:Rami Janini
                         v.1.0

Select: 1--> Camera Check  2--> For Motion Footage 3--> To Get Motion Alerts:3

~/domoticz/scripts/python/python-ring-doorbell-master/scripts $
`

With 1 and 3 nothing
With 2 error message

**Comment by JaniniRami07** [comment]
Oh okay, i have uploaded a new file to fix this problems yesterday so download the new PyRing.py
 file, it has more options too!

**Comment by Doudy** [comment]
Here is the result after modification:

My Device list is empty
With option 2 : error
With option 4 : Alarm is off!
With option 1 and 3 : nothing

`:~/domoticz/scripts/python/python-ring-doorbell-master/scripts $ python3 PyRing.py


          ___       ___  _
         / _ \__ __/ _ \(_)__  ___ _
        / ___/ // / , _/ / _ \/ _ `/
        /_/   \_, /_/|_/_/_//_/\_, /
                /___/            /___/
                        Author:Rami Janini
                                         v.1.1


Ring Email: xxx@xxx.xx
Ring Password:
Logged in as:  xxx@xxx.xx

Your Devices List:
[]

Select: 1--> Cameras Check  2--> Motion Footage  3--> Motion Alerts  4--> Alarm Controller  5--> Exit  :1


Select: 1--> Cameras Check  2--> Motion Footage  3--> Motion Alerts  4--> Alarm Controller  5--> Exit  :2

Traceback (most recent call last):
  File "PyRing.py", line 108, in <module>
    startProgram()
  File "PyRing.py", line 87, in startProgram
    GetVideo()
  File "PyRing.py", line 41, in GetVideo
    stickupCamera = RingCameras[0]
IndexError: list index out of range

~/domoticz/scripts/python/python-ring-doorbell-master/scripts $ python3 PyRing.py


          ___       ___  _
         / _ \__ __/ _ \(_)__  ___ _
        / ___/ // / , _/ / _ \/ _ `/
        /_/   \_, /_/|_/_/_//_/\_, /
                /___/            /___/
                        Author:Rami Janini
                                         v.1.1


Ring Email: xxx@xxx.xx
Ring Password:
Logged in as:  xxx@xxx.xx

Your Devices List:
[]

Select: 1--> Cameras Check  2--> Motion Footage  3--> Motion Alerts  4--> Alarm Controller  5--> Exit  :3


Select: 1--> Cameras Check  2--> Motion Footage  3--> Motion Alerts  4--> Alarm Controller  5--> Exit  :4

Alarm is off!

Select: 1--> Cameras Check  2--> Motion Footage  3--> Motion Alerts  4--> Alarm Controller  5--> Exit  :5

Thanks For using PyRing!
`

**Comment by JaniniRami07** [comment]
Do you have a security camera or a doorbell?

**Comment by Doudy** [comment]
a Ring Doorbell
[https://fr-fr.ring.com/](url)

**Comment by JaniniRami07** [comment]
Yup I see your problem, this program only works with Ring security cameras and I am working on the doorbell release i will send you a message when i update it so it works with doorbells!!

**Comment by Doudy** [comment]
OK thanks

**Comment by JaniniRami07** [comment]
Hey, download the new release it works with doorbells now!

**Comment by Doudy** [comment]
I test this
For option 1:
`Select: 1--> Cameras Check  2--> Motion Footage  3--> Motion Alerts  4--> Alarm Controller  5--> Exit  :1

Account ID: 4xxxxx2
Device ID: 6xxxxxxxxxxd
Family Type: doorbots
Device's Firmware: Up to Date
Device's Model: Doorbell
Device Subscription: False
Device's Adress: My Location, ,
Device's Wifi ESSID: WiFi-2.4-xxxx
Wifi Strength: -46
Battery Life: 100
Traceback (most recent call last):
  File "PyRing.py", line 185, in <module>
    startProgram()
  File "PyRing.py", line 159, in startProgram
    CameraCheck()
  File "PyRing.py", line 44, in CameraCheck
    print('Light Status: %s' % dev.lights)
AttributeError: 'RingDoorBell' object has no attribute 'lights'
`

**Comment by JaniniRami07** [comment]
I have updated it download the new release and try it out!

**Comment by Doudy** [comment]
Slightly different:
`Account ID: 4xxxxx2
Device ID: 6xxxxxxxxxxd
Family Type: doorbots
-bash: Select: : commande introuvable
Device's Firmware: Up to Date
Device's Model: Doorbell
Device Subscription: False
Device's Adress: My Location, ,
Device's Wifi ESSID: WiFi-2.4-xxxx
Wifi Strength: -46
Battery Life: 100
Connection Status: online
Account ID: 2xxxxx8
Device ID: fxxxxxxxxxx5
Family Type: chimes
Device's Firmware: Up to Date
Device's Model: Chime
Traceback (most recent call last):
  File "PyRing.py", line 183, in <module>
    startProgram()
  File "PyRing.py", line 157, in startProgram
    CameraCheck()
  File "PyRing.py", line 39, in CameraCheck
    print('Device Subscription: %s' % dev.has_subscription)
AttributeError: 'RingChime' object has no attribute 'has_subscription'
`

2x Account ID
2x Device ID
2x Device's Model but different (Doorbell and Chime)

**Comment by JaniniRami07** [comment]
I updated the code try it now!

**Comment by Doudy** [comment]
Also the same:
`Traceback (most recent call last):
  File "PyRing.py", line 183, in <module>
    startProgram()
  File "PyRing.py", line 157, in startProgram
    CameraCheck()
  File "PyRing.py", line 39, in CameraCheck
    print('Device Subscription: %s' % dev.has_subscription)
AttributeError: 'RingChime' object has no attribute 'has_subscription'
`

**Comment by JaniniRami07** [comment]
You didnt download the new code!

**Comment by Doudy** [comment]
New error:
~/domoticz/scripts/python/python-ring-doorbell-master/scripts/PyRing $ python3 PyRing.py 
`  File "PyRing.py", line 35
    print('Address:    %s' % dev.address)
                                        ^
TabError: inconsistent use of tabs and spaces in indentation
`

**Comment by JaniniRami07** [comment]
Download the new code and try it again

**Comment by Doudy** [comment]
Error at another line
`Traceback (most recent call last):
  File "PyRing.py", line 181, in <module>
    startProgram()
  File "PyRing.py", line 155, in startProgram
    CameraCheck()
  File "PyRing.py", line 42, in CameraCheck
    print('Battery Life: %s' % dev.battery_life)
AttributeError: 'RingChime' object has no attribute 'battery_life'
`

**Comment by JaniniRami07** [comment]
Download the new code and try it again

**Comment by Doudy** [comment]
MyDeviceList is empty
`Your Devices List:
[]
`

OK for option 1
`Select: 1--> Cameras Check  2--> Motion Footage  3--> Motion Alerts  4--> Alarm Controller  5--> Exit  :1

Account ID: 4xxxxx2
Address:    My Location, ,
Family:     doorbots
ID:         6xxxxxxxxxxd
Name:       Porte de devant
Timezone:
Wifi Name:  WiFi-2.4-xxxx
Wifi RSSI:  -45
Battery Life: 100`

Option 2-1:
`Traceback (most recent call last):
  File "PyRing.py", line 181, in <module>
    startProgram()
  File "PyRing.py", line 160, in startProgram
    GetVideo()
  File "PyRing.py", line 61, in GetVideo
    stickCamVideo()
  File "PyRing.py", line 46, in stickCamVideo
    stickupCamera = ringCameras[0]
IndexError: list index out of range
`
Option 2-2:
`Traceback (most recent call last):
  File "PyRing.py", line 181, in <module>
    startProgram()
  File "PyRing.py", line 160, in startProgram
    GetVideo()
  File "PyRing.py", line 65, in GetVideo
    doorbellCamVideo()
  File "PyRing.py", line 52, in doorbellCamVideo
    doorbell = ringCameras[0]
IndexError: list index out of range
`
Option 3-1:
Nothing

Option 3-2:
`Select: 1--> Security Camera Motion Alerts  2--> Doorbell Camera Motion Alerts  3--> Go Back : 2

Footage ID:     6695239829850163726
Kind:     motion
Answered:     False
Date/Time:     2019-05-26 07:49:59+00:00
----------------------------------------------------------------------------------------------------
Footage ID:     6695234890637773326
Kind:     motion
Answered:     False
Date/Time:     2019-05-26 07:30:49+00:00
---------------------------------------------`

Option 4-1:
Nothing

Option 4-2:
`After how many seconds do you want the alarm to be turned off?
`

**Comment by JaniniRami07** [comment]
you have a doorbell dont chose options for the security cameras

**Comment by Doudy** [comment]
OK
