### ISSUE TITLE
Account Login Error

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [JaniniRami07/PyRing#2]
`Ring Email: email@email.com
Traceback (most recent call last):
  File "PyRing.py", line 19, in <module>
    ringEmail = input('Ring Email: ')
  File "<string>", line 1
    email@email.com
                  ^
SyntaxError: invalid syntax`

**Comment by JaniniRami07** [comment]
Are you sure of your ring password and email?

You can try to log with your password and email on the ring website to make sure if it is right!
